// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SGHSS.Infra.Persistence;

#nullable disable

namespace SGHSS.Infra.Persistence.Migrations
{
    [DbContext(typeof(SGHSSDbContext))]
    partial class SGHSSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthUnitPatient", b =>
                {
                    b.Property<Guid>("HealthUnitsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientsId")
                        .HasColumnType("uuid");

                    b.HasKey("HealthUnitsId", "PatientsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("HealthUnitPatient", (string)null);
                });

            modelBuilder.Entity("HealthUnitProfessional", b =>
                {
                    b.Property<Guid>("HealthUnitsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfessionalsId")
                        .HasColumnType("uuid");

                    b.HasKey("HealthUnitsId", "ProfessionalsId");

                    b.HasIndex("ProfessionalsId");

                    b.ToTable("HealthUnitProfessional", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HealthUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Link")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("HealthUnitId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.AuditReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("AuditReports", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Bed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("HealthUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("HealthUnitId");

                    b.ToTable("Beds", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Consent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("ConsentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevocationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TermHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TermVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Consents", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.DigitalMedicalCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HealthUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("IcpSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("HealthUnitId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("DigitalMedicalCertificates", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.EletronicPrescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HealthUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("IcpSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("HealthUnitId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("EletronicPrescriptions", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.FinancialReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdministratorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalExpenses")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.ToTable("FinancialReports", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.HealthUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("HealthUnits", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.HomeCare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("HealthUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HealthUnitId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("HomeCares", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Hospitalization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AdmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DischargeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Hospitalizations", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("HealthUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("HealthUnitId");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdministratorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("MovementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("InventoryMovements", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.LogActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("HealthUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HealthUnitId");

                    b.HasIndex("UserId");

                    b.ToTable("LogActivities", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("MedicalRecords", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.MedicalRecordUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("HealthUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("HealthUnitId");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("MedicalRecordUpdates", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.ProfessionalSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalId")
                        .IsUnique();

                    b.ToTable("ProfessionalSchedules", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.SchedulePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfessionalScheduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalScheduleId")
                        .IsUnique();

                    b.ToTable("SchedulePolicies", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.ScheduleSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ProfessionalScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("ProfessionalScheduleId");

                    b.ToTable("ScheduleSlots", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SGHSS.Domain.Models.WeeklyWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("SchedulePolicyId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("SchedulePolicyId");

                    b.ToTable("WeeklyWindows", (string)null);
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Administrator", b =>
                {
                    b.HasBaseType("SGHSS.Domain.Models.User");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Patient", b =>
                {
                    b.HasBaseType("SGHSS.Domain.Models.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasDiscriminator().HasValue("Patient");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Professional", b =>
                {
                    b.HasBaseType("SGHSS.Domain.Models.User");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasDiscriminator().HasValue("Professional");
                });

            modelBuilder.Entity("HealthUnitPatient", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.HealthUnit", null)
                        .WithMany()
                        .HasForeignKey("HealthUnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Domain.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthUnitProfessional", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.HealthUnit", null)
                        .WithMany()
                        .HasForeignKey("HealthUnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Domain.Models.Professional", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Appointment", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.HealthUnit", null)
                        .WithMany("Appointments")
                        .HasForeignKey("HealthUnitId");

                    b.HasOne("SGHSS.Domain.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.AuditReport", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.Administrator", "CreatedBy")
                        .WithMany("AuditReports")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Bed", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.Hospitalization", "CurrentHospitalization")
                        .WithOne("Bed")
                        .HasForeignKey("SGHSS.Domain.Models.Bed", "AppointmentId");

                    b.HasOne("SGHSS.Domain.Models.HealthUnit", "HealthUnit")
                        .WithMany("Beds")
                        .HasForeignKey("HealthUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentHospitalization");

                    b.Navigation("HealthUnit");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Consent", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.User", "User")
                        .WithMany("Consents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.DigitalMedicalCertificate", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.Appointment", "Appointment")
                        .WithOne("DigitalMedicalCertificate")
                        .HasForeignKey("SGHSS.Domain.Models.DigitalMedicalCertificate", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Domain.Models.HealthUnit", "HealthUnit")
                        .WithMany("DigitalMedicalCertificates")
                        .HasForeignKey("HealthUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Domain.Models.Patient", "Patient")
                        .WithMany("DigitalMedicalCertificates")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Domain.Models.Professional", "Professional")
                        .WithMany("DigitalMedicalCertificates")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("HealthUnit");

                    b.Navigation("Patient");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.EletronicPrescription", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.Appointment", "Appointment")
                        .WithOne("EletronicPrescription")
                        .HasForeignKey("SGHSS.Domain.Models.EletronicPrescription", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Domain.Models.HealthUnit", "HealthUnit")
                        .WithMany("EletronicPrescriptions")
                        .HasForeignKey("HealthUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Domain.Models.Patient", "Patient")
                        .WithMany("EletronicPrescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Domain.Models.Professional", "Professional")
                        .WithMany("EletronicPrescriptions")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("HealthUnit");

                    b.Navigation("Patient");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.FinancialReport", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.Administrator", "Administrator")
                        .WithMany("FinancialReports")
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.HomeCare", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.HealthUnit", "HealthUnit")
                        .WithMany("HomeCares")
                        .HasForeignKey("HealthUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Domain.Models.Patient", "Patient")
                        .WithMany("HomeCares")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Domain.Models.Professional", "Professional")
                        .WithMany("HomeCares")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthUnit");

                    b.Navigation("Patient");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Hospitalization", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.Patient", "Patient")
                        .WithMany("Hospitalizations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.InventoryItem", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.HealthUnit", "HealthUnit")
                        .WithMany("InventoryItems")
                        .HasForeignKey("HealthUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthUnit");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.InventoryMovement", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.Administrator", "Administrator")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Domain.Models.InventoryItem", "InventoryItem")
                        .WithMany("InventoryMovement")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.LogActivity", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.HealthUnit", "HealthUnit")
                        .WithMany("LogActivities")
                        .HasForeignKey("HealthUnitId");

                    b.HasOne("SGHSS.Domain.Models.User", "User")
                        .WithMany("LogActivities")
                        .HasForeignKey("UserId");

                    b.Navigation("HealthUnit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.MedicalRecord", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.Patient", "Patient")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("SGHSS.Domain.Models.MedicalRecord", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.MedicalRecordUpdate", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.Appointment", "Appointment")
                        .WithOne("MedicalRecordUpdate")
                        .HasForeignKey("SGHSS.Domain.Models.MedicalRecordUpdate", "AppointmentId");

                    b.HasOne("SGHSS.Domain.Models.HealthUnit", "HealthUnit")
                        .WithMany("MedicalRecordUpdates")
                        .HasForeignKey("HealthUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Domain.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("Updates")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Domain.Models.Professional", "Professional")
                        .WithMany("MedicalRecordUpdates")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("HealthUnit");

                    b.Navigation("MedicalRecord");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Notification", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.User", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.ProfessionalSchedule", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.Professional", "Professional")
                        .WithOne("ProfessionalSchedule")
                        .HasForeignKey("SGHSS.Domain.Models.ProfessionalSchedule", "ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.SchedulePolicy", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.ProfessionalSchedule", "ProfessionalSchedule")
                        .WithOne("SchedulePolicy")
                        .HasForeignKey("SGHSS.Domain.Models.SchedulePolicy", "ProfessionalScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfessionalSchedule");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.ScheduleSlot", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.Appointment", "Appointment")
                        .WithOne("ScheduleSlot")
                        .HasForeignKey("SGHSS.Domain.Models.ScheduleSlot", "AppointmentId");

                    b.HasOne("SGHSS.Domain.Models.ProfessionalSchedule", "ProfessionalSchedule")
                        .WithMany("ScheduleSlots")
                        .HasForeignKey("ProfessionalScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("ProfessionalSchedule");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.WeeklyWindow", b =>
                {
                    b.HasOne("SGHSS.Domain.Models.SchedulePolicy", "SchedulePolicy")
                        .WithMany("WeeklyWindows")
                        .HasForeignKey("SchedulePolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchedulePolicy");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Appointment", b =>
                {
                    b.Navigation("DigitalMedicalCertificate");

                    b.Navigation("EletronicPrescription");

                    b.Navigation("MedicalRecordUpdate");

                    b.Navigation("ScheduleSlot");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.HealthUnit", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Beds");

                    b.Navigation("DigitalMedicalCertificates");

                    b.Navigation("EletronicPrescriptions");

                    b.Navigation("HomeCares");

                    b.Navigation("InventoryItems");

                    b.Navigation("LogActivities");

                    b.Navigation("MedicalRecordUpdates");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Hospitalization", b =>
                {
                    b.Navigation("Bed")
                        .IsRequired();
                });

            modelBuilder.Entity("SGHSS.Domain.Models.InventoryItem", b =>
                {
                    b.Navigation("InventoryMovement");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.MedicalRecord", b =>
                {
                    b.Navigation("Updates");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.ProfessionalSchedule", b =>
                {
                    b.Navigation("SchedulePolicy")
                        .IsRequired();

                    b.Navigation("ScheduleSlots");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.SchedulePolicy", b =>
                {
                    b.Navigation("WeeklyWindows");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.User", b =>
                {
                    b.Navigation("Consents");

                    b.Navigation("LogActivities");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Administrator", b =>
                {
                    b.Navigation("AuditReports");

                    b.Navigation("FinancialReports");

                    b.Navigation("InventoryMovements");
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DigitalMedicalCertificates");

                    b.Navigation("EletronicPrescriptions");

                    b.Navigation("HomeCares");

                    b.Navigation("Hospitalizations");

                    b.Navigation("MedicalRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("SGHSS.Domain.Models.Professional", b =>
                {
                    b.Navigation("DigitalMedicalCertificates");

                    b.Navigation("EletronicPrescriptions");

                    b.Navigation("HomeCares");

                    b.Navigation("MedicalRecordUpdates");

                    b.Navigation("ProfessionalSchedule")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
